
"""
This file is automatically generated by the dev_setup.py,
contains useful information about this package.
"""

__all__ = ['NAME', 'DESCRIPTION', 'LONG_DESCRIPTION', 'LONG_DESCRIPTION_CONTENT_TYPE', 'CLASSIFIERS', 'ZIP_SAFE', 'AUTHOR', 'VERSION', 'LICENSE', 'PYTHON_REQUIRES', 'URL', 'DOWNLOAD_URL', 'AUTHOR_EMAIL', 'PACKAGES', 'PLATFORMS', 'INSTALL_REQUIRES', 'ENTRY_POINTS']

NAME = 'btmod'
DESCRIPTION = 'Modify Python Built-in Types'
LONG_DESCRIPTION = '''btm - Built-in Types Modificator
================================

[This](https://github.com/nacho00112/btm) is a library written in pure python that allows you to modify the python built-in types easily.
For example:

```python
import btm
btm.addattr(int, "lol", 10)
print((1).lol) # Output: 10
```

How this works!?
----------------

- no C extensions, only pure python
- no preprocessors

Using the native library ctypes:
`ctypes.pythonapi._PyObject_GetDictPtr` do the trick.

Installation
------------
The simpliest way is using [pip](https://github.com/pypa/pip)

```bash
pip install btmod
```

or from github:

```bash
git clone https://github.com/nacho00112/btm
cd btm
python3 setup.py install
```

For test:

```bash
python3 test.py
```

Documentation
-------------

The documentation is available in [The btm documentation page](https://github.com/nacho00112/btm/tree/main/docs/index.md).

Contribution
------------

Contributions are welcome, see [CONTRIBUTE.md](https://github.com/nacho00112/btm/tree/main/CONTRIBUTE.md) for more information.

For bugs, questions, suggestions etc.
-------------------------------------

Go to [issues](https://github.com/nacho00112/btm/issues).

Contact
-------
- email
    - <thurealrubiogame@gmail.com>
- issues
    - [issues](https://github.com/nacho00112/btm/issues)

Creators
--------
- [Nacho](https://github.com/nacho00112)
- Only created by me!

'''
LONG_DESCRIPTION_CONTENT_TYPE = 'text/markdown'
CLASSIFIERS = ['Programming Language :: Python :: 3.7', 'Programming Language :: Python :: Implementation :: CPython']
ZIP_SAFE = False
AUTHOR = 'Nacho00112'
VERSION = '1.0.2'
LICENSE = 'mit'
PYTHON_REQUIRES = '>=3.7'
URL = 'https://github.com/nacho00112/btm'
DOWNLOAD_URL = 'https://github.com/nacho00112/btm/archive/v1.0.2.tar.gz'
AUTHOR_EMAIL = 'thurealrubiogame@gmail.com'
PACKAGES = ['btm']
PLATFORMS = 'any'
INSTALL_REQUIRES = []
ENTRY_POINTS = {'console_scripts': []}

